require("howe.plugins-setup")
require("howe.core.options")
require("howe.core.keymaps")
require("howe.core.colorscheme")
require("howe.plugins.comment")
-- require("howe.plugins.nvim-tree")
require("howe.plugins.neo-tree")
require("howe.plugins.lualine")
require("howe.plugins.telescope")
require("howe.plugins.nvim-cmp")
require("howe.plugins.lsp.mason")
require("howe.plugins.lsp.lspsaga")
require("howe.plugins.lsp.lspconfig")
require("howe.plugins.lsp.null-ls")
require("howe.plugins.autopairs")
require("howe.plugins.treesitter")
require("howe.plugins.gitsigns")
